# Generated by Django 5.0 on 2023-12-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('product_rating', models.DecimalField(decimal_places=3, max_digits=3, verbose_name='product rating')),
                ('shipping', models.CharField(max_length=100, verbose_name='shipping')),
                ('seller_rating', models.CharField(max_length=100, verbose_name='seller rating')),
                ('shippping_score', models.CharField(max_length=100, verbose_name='shipping score')),
            ],
        ),
    ]
