# Generated by Django 5.0 on 2023-12-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsi', '0002_alter_product_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='product rating'),
        ),
    ]
