# Generated by Django 5.0 on 2023-12-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsi', '0003_alter_product_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100, verbose_name='price'),
        ),
    ]
